#!/usr/bin/env python3
"""Generate the TypeScript wire view. Go subprocess/capability own Go DTOs.

Protocol/v1 is historical and is not rewritten by this generator.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
SCHEMA = json.loads((ROOT / 'schema.json').read_text())

def type_for(s):
    if not s or s.get('not') == {'type': 'null'}:
        return 'unknown'
    if 'const' in s:
        return json.dumps(s['const'])
    if 'enum' in s:
        return ' | '.join(json.dumps(v) for v in s['enum'])
    if 'anyOf' in s:
        return ' | '.join(type_for(v) for v in s['anyOf'])
    if isinstance(s.get('type'), list):
        return ' | '.join(type_for(dict(s, type=t)) for t in s['type'])
    if s.get('type') == 'null':
        return 'null'
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    kind = s.get('type')
    if kind in ('string', 'boolean', 'integer'):
        return {'string':'string','boolean':'boolean','integer':'number'}[kind]
    if kind == 'array':
        return 'Array<' + type_for(s['items']) + '>'
    if kind == 'object' and 'properties' not in s:
        return 'Record<string, ' + type_for(s.get('additionalProperties', {})) + '>'
    raise ValueError('unsupported schema: ' + repr(s))

out = ['// Code generated by protocol/v2/generate.py; DO NOT EDIT.',
       '// Runtime validators enforce the strict handshake and portable scope.',
       'export const PROTOCOL_VERSION = 2 as const;',
       "import type { ForwardContext } from './host-rpc.js';",  '']
for name, definition in SCHEMA['$defs'].items():
    if 'properties' not in definition:
        out.append(f'export type {name} = {type_for(definition)};')
    else:
        out.append(f'export interface {name} {{')
        for key, prop in definition['properties'].items():
            optional = key not in definition.get('required', [])
            out.append(f'  {key}{"?" if optional else ""}: {type_for(prop)};')
        out.append('}')
    out.append('')
text = '\n'.join(out).rstrip() + '\n'
(ROOT / 'wire.ts').write_text(text.replace("from './host-rpc.js'", "from '../../ts/packages/plugin-sdk/src/host-rpc.js'"))
(ROOT.parent.parent / 'ts/packages/plugin-sdk/src/wire.ts').write_text(text)
