#!/usr/bin/env python3
"""Generate reference wire types from the deliberately small JSON Schema subset.

Run from any directory. No external dependencies; unsupported forms fail loudly.
These views do not replace the existing Go author API during the draft phase.
"""
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent
SCHEMA = json.loads((ROOT / 'schema.json').read_text())

def type_for(s, lang):
    if not s:
        return 'json.RawMessage' if lang == 'go' else 'unknown'
    if 'const' in s and lang == 'ts':
        return json.dumps(s['const'])
    if isinstance(s.get('type'), list):
        nonnull = dict(s, type=next(t for t in s['type'] if t != 'null'))
        typ = type_for(nonnull, lang)
        return typ if lang == 'go' else typ + ' | null'
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    if s.get('contentEncoding') == 'base64':
        return '[]byte' if lang == 'go' else 'string'
    kind = s.get('type')
    if kind in ('string', 'boolean', 'integer'):
        return {'string': 'string', 'boolean': 'bool' if lang == 'go' else 'boolean', 'integer': 'int64' if lang == 'go' else 'number'}[kind]
    if kind == 'array':
        item = type_for(s['items'], lang)
        return '[]' + item if lang == 'go' else 'Array<' + item + '>'
    if kind == 'object' and 'properties' not in s:
        value = type_for(s.get('additionalProperties', {}), lang)
        return 'map[string]' + value if lang == 'go' else 'Record<string, ' + value + '>'
    raise ValueError('unsupported schema: ' + repr(s))

def go_name(key):
    return ''.join({'id':'ID','jsonrpc':'JSONRPC','http':'HTTP','mcp':'MCP','ok':'OK'}.get(word, word.title()) for word in key.split('_'))

go = ['// Code generated by generate.py; DO NOT EDIT.', '// Draft reference wire view; subprocess remains the existing runtime API.', 'package protocolv1', '', 'import "encoding/json"', '', f'const ProtocolVersion = {SCHEMA["x-protocol-version"]}', '']
ts = ['// Code generated by generate.py; DO NOT EDIT.', '// Draft reference wire view; byte bodies are base64 strings.', f'export const PROTOCOL_VERSION = {SCHEMA["x-protocol-version"]} as const;', '']
for name, definition in SCHEMA['$defs'].items():
    if 'properties' not in definition:
        go.append(f'type {name} {type_for(definition, "go")}')
        ts.append(f'export type {name} = {type_for(definition, "ts")};')
        continue
    go.append(f'type {name} struct {{')
    ts.append(f'export interface {name} {{')
    for key, prop in definition['properties'].items():
        optional = key not in definition.get('required', [])
        tag = key + (',omitempty' if optional else '')
        go_type = type_for(prop, 'go')
        if optional and '$ref' in prop:
            go_type = '*' + go_type
        go.append(f' {go_name(key)} {go_type} `json:"{tag}"`')
        ts.append(f'  {key}{"?" if optional else ""}: {type_for(prop, "ts")};')
    go.extend(['}', ''])
    ts.extend(['}', ''])
(ROOT / 'wire.go').write_text('\n'.join(go).rstrip() + '\n')
typescript = '\n'.join(ts).rstrip() + '\n'
(ROOT / 'wire.ts').write_text(typescript)
server_wire = ROOT.parent.parent / 'ts/packages/plugin-sdk/src/wire.ts'
server_wire.parent.mkdir(parents=True, exist_ok=True)
server_wire.write_text(typescript)
subprocess.run(['gofmt', '-w', str(ROOT / 'wire.go')], check=True)
