// Code generated by generate.py; DO NOT EDIT.
// Draft reference wire view; subprocess remains the existing runtime API.
package protocolv1

import "encoding/json"

const ProtocolVersion = 1

type RPCRequest struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int64           `json:"id,omitempty"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
}

type RPCError struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

type RPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int64           `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *RPCError       `json:"error,omitempty"`
}

type HostInfo struct {
	Version  string `json:"version"`
	Protocol int64  `json:"protocol"`
}

type InitParams struct {
	PluginDir string            `json:"plugin_dir"`
	DataDir   string            `json:"data_dir"`
	CacheDir  string            `json:"cache_dir"`
	Config    map[string]string `json:"config"`
	LogLevel  string            `json:"log_level"`
	HostInfo  HostInfo          `json:"host_info"`
	Granted   []string          `json:"granted,omitempty"`
	Identity  json.RawMessage   `json:"identity,omitempty"`
}

type InitResult struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Protocol    int64  `json:"protocol"`
}

type SkippedRegistration struct {
	Kind   string `json:"kind"`
	ID     string `json:"id"`
	Reason string `json:"reason"`
}

type LoadResult struct {
	SkippedRegistrations []SkippedRegistration `json:"skipped_registrations,omitempty"`
}

type EnvelopeOut struct {
	Type      string                     `json:"type"`
	Data      map[string]json.RawMessage `json:"data"`
	SessionID string                     `json:"session_id,omitempty"`
}

type CommandExecParams struct {
	Name      string          `json:"name"`
	SessionID string          `json:"session_id"`
	Args      string          `json:"args"`
	Identity  json.RawMessage `json:"identity,omitempty"`
}

type CommandExecResult struct {
	Action    string        `json:"action"`
	Content   string        `json:"content,omitempty"`
	Envelopes []EnvelopeOut `json:"envelopes,omitempty"`
}

type EventHandleParams struct {
	Type      string                     `json:"type"`
	Source    string                     `json:"source"`
	Data      map[string]json.RawMessage `json:"data"`
	SessionID string                     `json:"session_id,omitempty"`
	PreHook   bool                       `json:"pre_hook"`
	Identity  json.RawMessage            `json:"identity,omitempty"`
}

type EventHandleResult struct {
	Cancel    bool          `json:"cancel,omitempty"`
	Reason    string        `json:"reason,omitempty"`
	Envelopes []EnvelopeOut `json:"envelopes,omitempty"`
}

type CRUDParams struct {
	ResourceType string                     `json:"resource_type"`
	ID           string                     `json:"id,omitempty"`
	Data         map[string]json.RawMessage `json:"data,omitempty"`
	Filters      map[string]json.RawMessage `json:"filters,omitempty"`
}

type CRUDResult struct {
	Data json.RawMessage `json:"data"`
}

type CRUDListResult struct {
	Items []json.RawMessage `json:"items"`
}

type HealthResult struct {
	OK      bool   `json:"ok"`
	Message string `json:"message,omitempty"`
}

type MCPCallRequest struct {
	ToolName  string                     `json:"tool_name"`
	Arguments map[string]json.RawMessage `json:"arguments"`
	SessionID string                     `json:"session_id,omitempty"`
	Identity  json.RawMessage            `json:"identity,omitempty"`
}

type MCPCallResult struct {
	Content   json.RawMessage `json:"content"`
	IsError   bool            `json:"is_error,omitempty"`
	Envelopes []EnvelopeOut   `json:"envelopes,omitempty"`
}

type HTTPRequest struct {
	Method    string            `json:"method"`
	Path      string            `json:"path"`
	RawPath   string            `json:"raw_path,omitempty"`
	RawQuery  string            `json:"raw_query,omitempty"`
	Query     map[string]string `json:"query,omitempty"`
	Headers   map[string]string `json:"headers,omitempty"`
	Body      []byte            `json:"body,omitempty"`
	SessionID string            `json:"session_id,omitempty"`
	Identity  json.RawMessage   `json:"identity,omitempty"`
}

type HTTPResponse struct {
	Status  int64             `json:"status"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    []byte            `json:"body,omitempty"`
}

type MigrateParams struct {
	FromVersion string `json:"from_version"`
	ToVersion   string `json:"to_version"`
	DataDir     string `json:"data_dir"`
}

type MigrateResult struct {
	Notes []string `json:"notes,omitempty"`
}

type CapabilityRequest struct {
	Name     string          `json:"name"`
	Reason   string          `json:"reason,omitempty"`
	Optional bool            `json:"optional,omitempty"`
	Metadata json.RawMessage `json:"metadata,omitempty"`
}

type EmptyParams struct {
}

type OKResult struct {
	OK bool `json:"ok"`
}
