// Code generated by protocol/v2/generate.py; DO NOT EDIT.
// Reserved hooks/1 DTOs; availability requires independent negotiation.
import type { ForwardContext } from './host-rpc.js';
import type { RuntimeIdentity } from './wire.js';

export type HookFailureCode = "remote_not_allowed" | "latency_budget_exceeded" | "schema_mismatch" | "profile_unavailable" | "stale_scope" | "stale_binding" | "capacity_exhausted" | "deadline_exceeded" | "caller_cancelled" | "depth_exceeded" | "callback_cycle" | "transport_failure" | "handler_panic" | "invalid_output" | "handler_error";

export type HookKind = "action" | "filter";

export type HookMode = "sequential" | "parallel" | "bail" | "waterfall" | "async" | "after_commit";

export type HookStatus = "ok" | "cancelled" | "approval_required" | "failed" | "unavailable";

export interface HookScope {
  incarnation: RuntimeIdentity;
  registration_id: string;
}

export interface HookTrace {
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
}

export interface HookFailure {
  code: HookFailureCode;
  message?: string;
}

export interface HookErrorData {
  contract: "hooks/1";
  code: "invalid_params" | "profile_unavailable" | "invalid_request" | "parse_error" | "method_not_found";
  field?: string;
}

export interface HookHandleParams {
  invocation_id: string;
  catalog_version: string;
  hook: string;
  schema_digest: string;
  kind: HookKind;
  mode: HookMode;
  scope: HookScope;
  context: ForwardContext;
  // Opaque JSON: literal bytes are preserved by the runtime codec.
  payload: unknown;
  metadata: Record<string, string>;
  deadline: string;
  aggregate_budget_ms: number;
  depth: number;
  trace: HookTrace;
  root_invocation_id: string;
  parent_invocation_id?: string;
}

export interface HookHandleResult {
  invocation_id: string;
  status: HookStatus;
  // Opaque JSON: literal bytes are preserved by the runtime codec.
  payload?: unknown;
  reason?: string;
  error?: HookFailure;
}

export interface HookHandleBatchParams {
  items: Array<HookHandleParams>;
}

export interface HookHandleBatchResult {
  items: Array<HookHandleResult>;
}
