// Code generated by generate.py; DO NOT EDIT.
// Draft reference wire view; byte bodies are base64 strings.
export const PROTOCOL_VERSION = 1 as const;

export interface RPCRequest {
  jsonrpc: "2.0";
  id?: number;
  method: string;
  params?: unknown;
}

export interface RPCError {
  code: number;
  message: string;
  data?: unknown;
}

export interface RPCResponse {
  jsonrpc: "2.0";
  id: number;
  result?: unknown;
  error?: RPCError;
}

export interface HostInfo {
  version: string;
  protocol: number;
}

export interface InitParams {
  plugin_dir: string;
  data_dir: string;
  cache_dir: string;
  config: Record<string, string> | null;
  log_level: string;
  host_info: HostInfo;
  granted?: Array<string> | null;
  identity?: unknown;
}

export interface InitResult {
  id: string;
  name: string;
  version: string;
  description: string;
  protocol: number;
}

export interface SkippedRegistration {
  kind: string;
  id: string;
  reason: string;
}

export interface LoadResult {
  skipped_registrations?: Array<SkippedRegistration> | null;
}

export interface EnvelopeOut {
  type: string;
  data: Record<string, unknown> | null;
  session_id?: string;
}

export interface CommandExecParams {
  name: string;
  session_id: string;
  args: string;
  identity?: unknown;
}

export interface CommandExecResult {
  action: string;
  content?: string;
  envelopes?: Array<EnvelopeOut> | null;
}

export interface EventHandleParams {
  type: string;
  source: string;
  data: Record<string, unknown> | null;
  session_id?: string;
  pre_hook: boolean;
  identity?: unknown;
}

export interface EventHandleResult {
  cancel?: boolean;
  reason?: string;
  envelopes?: Array<EnvelopeOut> | null;
}

export interface CRUDParams {
  resource_type: string;
  id?: string;
  data?: Record<string, unknown> | null;
  filters?: Record<string, unknown> | null;
}

export interface CRUDResult {
  data: unknown;
}

export interface CRUDListResult {
  items: Array<unknown> | null;
}

export interface HealthResult {
  ok: boolean;
  message?: string;
}

export interface MCPCallRequest {
  tool_name: string;
  arguments: Record<string, unknown> | null;
  session_id?: string;
  identity?: unknown;
}

export interface MCPCallResult {
  content: unknown;
  is_error?: boolean;
  envelopes?: Array<EnvelopeOut> | null;
}

export interface HTTPRequest {
  method: string;
  path: string;
  raw_path?: string;
  raw_query?: string;
  query?: Record<string, string> | null;
  headers?: Record<string, string> | null;
  body?: string;
  session_id?: string;
  identity?: unknown;
}

export interface HTTPResponse {
  status: number;
  headers?: Record<string, string> | null;
  body?: string;
}

export interface MigrateParams {
  from_version: string;
  to_version: string;
  data_dir: string;
}

export interface MigrateResult {
  notes?: Array<string> | null;
}

export interface CapabilityRequest {
  name: string;
  reason?: string;
  optional?: boolean;
  metadata?: unknown;
}

export interface EmptyParams {
}

export interface OKResult {
  ok: boolean;
}
