// Code generated by protocol/v2/generate.py; DO NOT EDIT.
// Runtime validators enforce the strict handshake and portable scope.
export const PROTOCOL_VERSION = 2 as const;
import type { ForwardContext } from './host-rpc.js';

export interface RPCRequest {
  jsonrpc: "2.0";
  id?: RPCID;
  method: string;
  params?: unknown;
}

export interface RPCError {
  code: number;
  message: string;
  data?: unknown;
}

export interface RPCResponse {
  jsonrpc: "2.0";
  id: RPCID | null;
  result?: unknown;
  error?: RPCError;
}

export interface HostInfo {
  version: string;
  protocol: 2;
}

export interface InitParams {
  plugin_dir: string;
  data_dir: string;
  cache_dir: string;
  config: Record<string, string>;
  log_level: "debug" | "info" | "warn" | "error";
  host_info: HostInfo;
  capability_contract: 1;
  incarnation: RuntimeIdentity;
  grants: GrantSet;
  identity?: unknown;
  host_services?: HostServices;
  hooks_profile?: HooksProfile;
  context?: ForwardContext;
}

export interface InitResult {
  id: string;
  name: string;
  version: string;
  description: string;
  protocol: 2;
  capability_contract: 1;
  reverse_rpc_version?: 1;
  hooks_profile_version?: 1;
}

export interface SkippedRegistration {
  kind: string;
  id: string;
  reason: string;
}

export interface LoadResult {
  skipped_registrations?: Array<SkippedRegistration>;
}

export interface EnvelopeOut {
  type: string;
  data: Record<string, unknown> | null;
  session_id?: string;
}

export interface CommandExecParams {
  name: string;
  session_id: string;
  args: string;
  identity?: unknown;
  context?: ForwardContext;
}

export interface CommandExecResult {
  action: string;
  content?: string;
  envelopes?: Array<EnvelopeOut>;
}

export interface EventHandleParams {
  type: string;
  source: string;
  data: Record<string, unknown>;
  session_id?: string;
  pre_hook: boolean;
  identity?: unknown;
  context?: ForwardContext;
}

export interface EventHandleResult {
  cancel?: boolean;
  reason?: string;
  envelopes?: Array<EnvelopeOut>;
}

export interface CRUDParams {
  resource_type: string;
  id?: string;
  data?: Record<string, unknown>;
  filters?: Record<string, unknown>;
  context?: ForwardContext;
}

export interface CRUDResult {
  data: Record<string, unknown> | null;
}

export interface CRUDListResult {
  items: Array<Record<string, unknown> | null>;
}

export interface HealthResult {
  ok: boolean;
  message?: string;
}

export interface MCPCallRequest {
  tool_name: string;
  arguments: Record<string, unknown>;
  session_id?: string;
  identity?: unknown;
  context?: ForwardContext;
}

export interface MCPCallResult {
  content: unknown;
  is_error?: boolean;
  envelopes?: Array<EnvelopeOut>;
}

export interface HTTPRequest {
  method: string;
  path: string;
  raw_path?: string;
  raw_query?: string;
  query?: Record<string, string>;
  headers?: Record<string, string>;
  body?: string;
  session_id?: string;
  identity?: unknown;
  context?: ForwardContext;
}

export interface HTTPResponse {
  status: number;
  headers?: Record<string, string> | null;
  body?: string;
}

export interface MigrateParams {
  from_version: string;
  to_version: string;
  data_dir: string;
  context?: ForwardContext;
}

export interface MigrateResult {
  notes?: Array<string>;
}

export interface CapabilityRequest {
  name: string;
  reason?: string;
  optional?: boolean;
  metadata?: unknown;
}

export interface EmptyParams {
  context?: ForwardContext;
}

export interface OKResult {
  ok: boolean;
}

export interface RuntimeIdentity {
  host_instance: string;
  owner_id: string;
  owner_generation: number;
}

export interface Grant {
  grant_id: string;
  name: string;
  schema_version: number;
  scope: unknown;
  host_instance: string;
  owner_id: string;
  owner_generation: number;
  audience: string;
  issued_at: string;
  expires_at: string;
  policy_revision: string;
}

export type GrantSet = Array<Grant>;

export interface HooksProfile {
  hooks_profile_version: 1;
}

export interface HostServices {
  reverse_rpc_version: 1;
  incarnation: RuntimeIdentity;
  methods: Array<string>;
  limits: HostServiceLimits;
}

export interface HostServiceLimits {
  host_to_plugin_inflight: number;
  plugin_to_host_inflight: number;
  host_global_inflight: number;
  control_slots: number;
  max_frame_bytes: number;
  max_queued_write_bytes: number;
  write_timeout_ms: number;
  max_depth: number;
  method_timeout_ms: Record<string, number>;
}

export type RPCID = string | number;
